server:
  port: 8761

spring:
  application:
    name: TRADING-EUREKA-SERVER
  cloud:
    config:
      profile: local
      name: eureka-server
  config:
    import:
      - optional:configserver:https://setlog.net/trading-config-server/

